# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Constructor
version:      1.1.1
version_from: Constructor.pm
installdirs:  site
requires:
    Class::Accessor:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
